### ISSUE TITLE
pack

### ISSUE THREAD

**Issue by vladon** [vpiotr/decimal_for_cpp#15]
```
    decimal &pack(int64 beforeValue, int64 afterValue) {
      if (Prec > 0) {
        m_value = beforeValue * DecimalFactor<Prec>::value;
        m_value += (afterValue % DecimalFactor<Prec>::value);
       } else
        m_value = beforeValue * DecimalFactor<Prec>::value;
      return *this;
    }
```

Sorry, but are you sure that this works? I mean taking a modulo for `afterValue`?

Suppose you have `pack(123, 456)` with precision of 2. You will got `123.04` as a result.

And second question is about negative numbers, what if `beforeValue < 0`? Then when calling `pack(-12, 34)` with precision of 2, you will got `-1200 + 34 == 1166`.

**Comment by vpiotr** [comment]
Hi, 

1) pack(123, 456), prec<2> is wrong. See documentation-in-comment for pack() function and "after" value description:

    /// Combines two parts (before and after decimal point) into decimal value
    /// \param[in] before value before decimal point
    /// \param[in] after value after decimal point multiplied by 10^prec
    /// \result Returns *this

In that case:
* calculated result of pack(123, 456) will be 123,56
* value 456 is not "after value"  multiplied by 100

This function does not handle rounding - and it cannot do it. 
It assumes you follow function requirements.

See example:

```
decimal<4> d;
/* 1 */ BOOST_CHECK(d.pack(1,1) == decimal<4>("1.0001")); // OK
/* 2 */ BOOST_CHECK(d.pack(1,/*000*/1) == decimal<4>("1.0001")); // OK
/* 3 */ BOOST_CHECK(d.pack(1,/*0000*/1) == decimal<4>("1.0001")); // OK, but if you meant "1.00001" or "1.01" - in that case it's an error
```

Also it's wrong to add any handling for "after" numbers > 10^prec, because it will work only for values with first digit > 0, for other numbers such a test will not work and error will go undetected. 

I'll add clarification comment - "after" value cannot be higher or equal to 10^prec.

2) second case, `pack(-12, 34)`, is not correct according to included unit tests, see:

```
  BOOST_CHECK(d.pack(-1,-5121) == decimal<4>(-1.5121));
  BOOST_CHECK(d.pack(-1,5121) != decimal<4>(-1.5121));
  BOOST_CHECK(d.pack(1,-5121) != decimal<4>(-1.5121));
```

You need to provide both numbers negative - I'll document this requirement in comment too.

**Comment by vpiotr** [comment]
For (1) see pack_rounded - where you specify input precision.
I managed also to correct "fromString" which from now performs rounding when precision of input value is higher then output precision.
