### ISSUE TITLE
templated operators do not work

### ISSUE THREAD

**Issue by mteske** [vpiotr/decimal_for_cpp#31]
for example  template<int Prec2>
    decimal & operator+=(const decimal<Prec2> &rhs) : 

           dec::decimal<8> p8(1);
           dec::decimal<4> p4(0);

            p8 += p4;
            p4 += p8;

both operations fail on either one of the static asserts. They cannot removed, because else one branch creates an infinite template recursion. This is on linux with gcc 7.3.

**Comment by mteske** [comment]
[decimal_diff.txt](https://github.com/vpiotr/decimal_for_cpp/files/2375940/decimal_diff.txt)
This fixes the issue, I think (credits go to my collegue Clemens Misch)

**Comment by vpiotr** [comment]
Hi, thanks for this fix. 

This is good direction but there are some issues to be considered:
* there should be compilation error in this case: p4 += p8
* this compilation error must be meaningful  
* m_value is preferred over getUnbiased, the latter is a API method for persistence

**Comment by mteske** [comment]
Hi,
thanks for the reply. If I understand you correct, p4 += p8 should give a compilation error because you possibly lose precision? This might depend on the use case, for my task the (pre-existing) code that rounds the result is fine. Ideally one could configure the behaviour with a template parameter.
 We had to use getUnbiased() because else the compiler would complain about m_value being private.
We forgot assignment operators, I have it fixed here, it's done in a similar way.

**Comment by vpiotr** [comment]
Hi,

There are the following common rules for this lib:
* on value copy execution without data loss is preferred (see constructor with string argument)
* when p4 is mixed with another p4, rounding occurs automatically
* when p4 is mixed with p8, it is possible only if there is no rounding, otherwise you should explicit specify (using decimal_cast) when and how the rounding should be executed. 
* so if you mix p8 and p4 and there is no requirement for rounding,  statement can be compiled correctly (only if rounding detection can be performed at compile time)
* and if you mix p8 and p4 without decimal_cast and rounding can happen, compilation error should occur 

This is kind of "strong typing" which is helpful for decimal calculations in financial code.

**Comment by vpiotr** [comment]
Updated code accordingly. Please see  unit test decimalTypeLevel and readme for more information.
