### ISSUE TITLE
Is it compatible with IEEE 754-2008?

### ISSUE THREAD

**Issue by ivan-volnov** [vpiotr/decimal_for_cpp#43]
Hello!

Can you explain the difference between your implementation vs [IEEE 754-2008](https://en.wikipedia.org/wiki/IEEE_754)?
What about [Intel Decimal Floating-Point Math Library](https://software.intel.com/content/www/us/en/develop/articles/intel-decimal-floating-point-math-library.html)?
Have you done some benchmarks of the library?

**Comment by vpiotr** [comment]
There is no relationship between this library and IEEE 754-2008.
I haven't used Intel's library.

**Comment by Frafjord** [comment]
### Difference between decimal_for_cpp and IEEE 754-2008

In the link you provided decimal64 is the data type that is closest to decimal_for_cpp. They are both 64 bit and they are both 10 based.

### Floating point vs Fixed point

The main difference between them is that decimal64 is floating point while decimal_for_cpp is fixed point.

#### decimal_for_cpp
With decimal_for_cpp you choose how many decimal positions you want when you declare the variable. If you want four decimal places you declare the variable like this:

``` c++
dec::decimal<4> myValue;
```

Because the precision is known at compile time, and doesn't change, the precision is stored as part of the data type definition, and doesn't need to be stored in the variable, and all the 64 bits can be used to represent the number itself.

This means that the declared variable can hold any number between -922337203685477.5808 and 922337203685477.5807 with a precision of four through the whole range.

#### decimal64
decimal64 is a floating point number. This means that you don't specify what precision you want, but some of the 64 bits will be used to specify what precision you get.

This means that a decimal64 can hold a larger range of numbers, but the precision will be bad for numbers that are far away from 0. The precision will be very high for numbers close to 0.
