### ISSUE TITLE
unable to change precision of existing variable

### ISSUE THREAD

**Issue by omerbrandis** [vpiotr/decimal_for_cpp#62]
hi.

I've been using this lib (1.18) for a few months now.  ( thanks for building it btw).

now I've encountered a situation were I've realized I need to change many existing decimal2 variables to decimal4 .
when I change one of them, i get the complication error  
..../decimal.h:793: error: no matching function for call to ‘dec::decimal<4>::decimal(const dec::decimal<2>&)’
  793 |         return (*this == static_cast<decimal>(rhs));
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~

using gcc/g++ 9.4.0.

I was not able to find in my code cases of  of the changed variable construction using another dec2 variable, that would match the error msg [i.e  my_dec4_variable = decimal4(old_dec2_variable)].  
the compiler is unable to pinpoint the location of the error ( I guess its because this is a template class).
but there are many assignments [ i.e. changed_dec4_variable = .... unchanged_dec2_variable ... ; ]

I was wondering how I can proceed.
i'd rather avoid manually changing a lot of code to add explicit decimal_cast<4>.
id rather have some sort of built in support for the required assignment. ( an overload of the constructor or assignment operator  ???)

I noticed config parameter DEC_TYPE_LEVEL, but did not understand if/how it can be applied here.
 
can anyone suggest a simple way to proceed?
:-)

**Comment by omerbrandis** [comment]
tried wrapping decimal4 with my own class to add support for the missing constructor :
```
class MyDecimal4:public dec::decimal4
{
    MyDecimal4(const dec::decimal2 & rhs):dec::decimal4(dec::decimal_cast<4>(rhs)) {};
};

```
but this lead to other compilation errors for missing overloads
( error: could not convert ‘{-1}’ from ‘<brace-enclosed initializer list>’ to ‘MyDecimal4’
 ....   <brace-enclosed initializer list>)

seems even more complicated.... :-(

**Comment by vpiotr** [comment]
Mixing two variables with different precision without casting is intentionally failing because it can lead to precision loss.

So assignment operator exists, but constructor not.

See examples:

```
decimal<2> d2("12.03");
decimal<4> d4("123.0103");

// not possible: decimal<2> d2x(d4);

// possible via assignment operator:
decimal<2> d2a;
d2a = d4;

// possible via decimal_cast:
decimal<2> d2b(decimal_cast<2>(d4));

// possible via toString (slow):
decimal<2> d2c(toString(d4));
```

You can verify which operators are supported for mixed precision expressions when you search for "<Prec2>" in the decimal.h file.

If you really need copying constructor for mixed precision, you can fork the library and add code based on assignment operator which supports mixed precision statements:
`decimal & operator=(const decimal<Prec2> &rhs)`
but this may lead to unintentional conversions and I'm not willing to merge such code.

**Comment by omerbrandis** [comment]
thank you vpiotr.
